name: geoffreyd
favicon: null
layout_spectrum: 0.031304683070629835
typography_spectrum: 0.4547812081873417
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5648828360717744
  lightness: 0.9182045750785619
  saturation: 0.25870028720237315
  rhythmicContrast: 0.5687169113662094
purpose: []
